# Generated by Django 4.0.4 on 2022-06-20 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schooluser',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AddField(
            model_name='schooluser',
            name='is_moderator',
            field=models.BooleanField(default=False, verbose_name='Доступ модератора'),
        ),
        migrations.AddField(
            model_name='schooluser',
            name='is_teacher',
            field=models.BooleanField(default=False, verbose_name='Доступ учителья'),
        ),
    ]
