# Generated by Django 4.0.4 on 2022-06-20 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_alter_schooluser_options_schooluser_is_moderator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schooluser',
            name='is_moderator',
            field=models.BooleanField(default=False, verbose_name='Статус модератора'),
        ),
        migrations.AlterField(
            model_name='schooluser',
            name='is_teacher',
            field=models.BooleanField(default=False, verbose_name='Статус учителья'),
        ),
    ]
