# Generated by Django 4.0.4 on 2022-06-18 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Заголовок новости')),
                ('image', models.ImageField(upload_to='news_images', verbose_name='Изображение новости')),
                ('short_desc', models.CharField(max_length=500, verbose_name='Короткое описание')),
                ('full_text', models.TextField(verbose_name='Полный текст новости')),
                ('author', models.CharField(max_length=128, verbose_name='Автор')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.CharField(blank=True, max_length=128, verbose_name='Преподаватель'),
        ),
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.coursecategory', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.CharField(max_length=500, verbose_name='Описание курса'),
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(upload_to='course_images', verbose_name='Изображение курса'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Имя курса'),
        ),
        migrations.AlterField(
            model_name='coursecategory',
            name='description',
            field=models.CharField(blank=True, max_length=255, verbose_name='Описание'),
        ),
    ]
