# Generated by Django 4.0.4 on 2022-06-20 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_news_course_teacher_alter_course_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Курс', 'verbose_name_plural': 'Курсы'},
        ),
        migrations.AlterModelOptions(
            name='coursecategory',
            options={'verbose_name': 'категория курсов', 'verbose_name_plural': 'категории курсов'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Новости', 'verbose_name_plural': 'Новости'},
        ),
    ]
