# Generated by Django 4.0.4 on 2022-06-23 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_course_options_alter_coursecategory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='lessons',
            field=models.JSONField(null=True, verbose_name='Данные урока'),
        ),
    ]
