# Generated by Django 4.0.4 on 2022-06-25 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_course_lessons'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='lesson_data',
            field=models.JSONField(null=True, verbose_name='Данные курса'),
        ),
    ]
