# Generated by Django 4.0.4 on 2022-06-25 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_course_lesson_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='lessons',
        ),
        migrations.AddField(
            model_name='course',
            name='lessons_list',
            field=models.JSONField(null=True, verbose_name='Список урокв'),
        ),
    ]
