# Generated by Django 4.0.4 on 2022-07-20 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_remove_course_lessons_course_lessons_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(verbose_name='Описание курса'),
        ),
        migrations.AlterField(
            model_name='course',
            name='lessons_list',
            field=models.JSONField(null=True, verbose_name='Список уроков'),
        ),
    ]
